### ISSUE TITLE
Confusion with vscode-icons/vscode-icons

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-icons#5]
Hi there! I just wanted to say that I stumbled upon this repo while looking for https://github.com/vscode-icons/vscode-icons

It may be worth changing the repo name to something a bit more descriptive (like `vscode-icon-resources`) so that other folks don't fall to the same confusion.

Feel free to close this if you don't agree.

**Comment by miguelsolorio** [comment]
Thanks for the feedback! The VS Code team labels all of our repos with `vscode-`, and theoretically this repo makes more sense for `vscode-icons` since it's the official repo for our icons. 

It would make more sense for [vscode-icons/vscode-icons](https://github.com/vscode-icons/vscode-icons) to rename to something more descriptive like the rest of the file icons on VS Code (like [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme), [Nomo Dark Icon Theme](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-icontheme-nomo-dark), [Keen Neutral Icon Theme](https://marketplace.visualstudio.com/items?itemName=keenethics.keen-neutral-icon-theme), etc.)

**Comment by TylerLeonhardt** [comment]
> It would make more sense for vscode-icons/vscode-icons to rename to something more descriptive like the rest of the file icons on VS Code (like Material Icon Theme, Nomo Dark Icon Theme, Keen Neutral Icon Theme, etc.)

I'll let you discuss that with them if you think their name should be changed. I just found it confusing winding up here.
