### ISSUE TITLE
Color library isn't accessible

### ISSUE THREAD

**Issue by bendera** [microsoft/vscode-icons#7]
First of all, thank you for sharing your Figma project! Unfortunately, it seems the color library is not accessible. I didn't find that option in the right panel and when I tried to open from the hamburger menu I got this window:

![vscode-icons-library](https://user-images.githubusercontent.com/3748508/65545636-0e145980-df16-11e9-99d5-1d44a707f48c.png)

Could you check the sharing settings?

**Comment by miguelsolorio** [comment]
@bendera that's a good point, I'll work on adding these styles to the file directly (I have a separate file where I store the originals).

**Comment by miguelsolorio** [comment]
I've added the colors to the file (since it sits in my team library and Figma doesn't allow external files to access that yet):

<img width="271" alt="image" src="https://user-images.githubusercontent.com/35271042/65547474-6889c780-dece-11e9-9a11-84f4f8f08acd.png">

However, when you duplicate this file the color links will break:

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/35271042/65547543-82c3a580-dece-11e9-9bbc-37f3fb2cb06d.png">


But you can still access the color palettes now:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/35271042/65547567-92db8500-dece-11e9-847f-2fbcc5d9392a.png">

Hopefully this helps!
